### PR TITLE
UserKeyServiceImpl convert function does not support EdDSA Algorithm

### PR DESCRIPTION
**Pull request by gmulhearn**
#What is this PR for?
See Issue #4 

## Overview or reasons
Please see Issue #4

## Tasks
- added a case for the EdDSA algorithm.

## Result
- I have tested this with a custom authenticator (i.e. one that works on local servers / non https servers) forced to use EdDSA, and confirmed that it works for EdDSA keys.

### CODE REVIEW

**Review by kj84park — APPROVED** [review]

**Comment by kj84park** [comment]
LGTM!  Thank you for your contribution!

**Comment by kj84park** [comment]
For merging, could you sign the Contributor License Agreement?

**Comment by gmulhearn** [comment]
hey there, thanks for your review. I have signed the CLA thru the website the github bot links, but the github bot doesn't seem to recognise/update? When I click on the link now I get "You have agreed to the CLA for line/line-fido2-server". Is there anything I can do to update the bot?

**Comment by gmulhearn** [comment]
ah whoops! i'd made a commit from another account and had to sign with both. all fixed now

**Pull request merged**
